# 3-8
travel_list = ['Sirilanka','Tailand','Losangeles','Brazil','Australia']
print(travel_list)
print(sorted(travel_list))
print(travel_list)
print(sorted(travel_list,reverse=True))
print(travel_list)
travel_list.reverse()
print(travel_list)
travel_list.reverse()
print(travel_list)
travel_list.sort()
print(travel_list)
travel_list.sort(reverse=True)
print(travel_list)